###
# @name getFoo
GET http://localhost:5001/demo/foo
Content-Type: application/json

###
# @name addNumbers
GET http://localhost:5001/demo/add?num1=4&num2=8
Content-Type: application/json

###
# @name getMenu
GET http://localhost:5001/menu
Content-Type: application/json

###
# @name getMenuTotalPrice
GET http://localhost:5001/menu/1/total-price
Content-Type: application/json

###
# @name deleteMenu
DELETE http://localhost:5001/menu/1
Content-Type: application/json

###
# @name getProduct
GET http://localhost:5001/product
Content-Type: application/json

###
# @name getProductById
GET http://localhost:5001/product/1
Content-Type: application/json

###
# @name getProductByType
GET http://localhost:5001/product/type?type=Drink
Content-Type: application/json

###
# @name createProduct
POST http://localhost:5001/product
Content-Type: application/json

{
  "price": 9.49,
  "hot": true,
  "name": "Pizza",
  "type": "Food",
  "vegetarian": true,
  "ingredients": [
    {
      "description": "Dough",
      "allergens": [
        "Gluten"
      ]
    },
    {
      "description": "Sauce",
      "allergens": []
    },
    {
      "description": "Cheese",
      "allergens": [
        "Dairy"
      ]
    }
  ]
}